# Factorización de Crout

#### Nombre: Benites Onofre Fernando Gabriel

In [1]:
# Librerías a utilizar
import numpy as np
import random

- ### Una función que encuentre la factorización PLU de una matriz A. La función debe verificar que la matriz sea cuadrada e invertible. La prueba para saber si A es invertible debe hacerse con la condición del máximo distinto de cero.

Recordemos que la Factorización PLU, factoriza la matríz A como la multiplicación de tres matrices. Dicha factorización está dada por: $$A=PLU$$

In [2]:
def square_matrix(A, num_row, num_col):
    if num_row == num_col:
        return True
    else:
        return False

In [3]:
def factorizacion_PLU(A): 
    # El formato de A es [[a,b], [c,d], [],...]
    A_matrix = np.matrix(A)
    A_matrix = A_matrix.astype(float)
    # ¿La matríz es cuadrada e invertible?
    num_rows, num_cols = A_matrix.shape
    
    if square_matrix(A_matrix, num_rows, num_cols):
        print(f'La matriz \n {A_matrix} es cuadrada.')
    else:
        return 'La matriz no es cuadrada por lo tanto no es invertible.'

    # Declaramos las matrices P, L y U
    P, L, U_matrix = np.identity(num_rows), np.zeros((num_rows,num_cols)), A_matrix.copy()
    
    # Paso 2, 3, 4 y 5 del algoritmo 
    count = 0
    while count < num_cols - 1: #tenemos que detenernos una columna antes 

        U_columna = U_matrix[count:,count]
        U_columna = np.reshape(U_columna, num_rows-count)
        max_value = np.amax(abs(U_columna)) 
        if max_value == 0: 
            return f'''Tenemos que en la columna {count + 1}, es decir {U_columna} 
                    el máximo es cero, entonces es singular y no se encuentra 
                    factorización'''        
        index_y, index_x = np.where(abs(U_matrix[count:,count]) == max_value)
        
        #cambio de renglones
        U_matrix[[index_x[0]+count, index_y[0]+count]] = U_matrix[[index_y[0]+count, index_x[0]+count]]
        P[[index_y[0]+count, index_x[0]+count]] = P[[index_x[0]+count, index_y[0]+count]]
        L[[index_y[0]+count, index_x[0]+count]] = L[[index_x[0]+count, index_y[0]+count]]

        for i in range(count+1, num_rows):
            L[i,count] = U_matrix[i,count] / U_matrix[count,count]
            U_matrix[i, :] = U_matrix[i, :] - L[i,count]*U_matrix[count,:]

        count += 1        
    else:
        print('La matríz no es singular')
    
    L = L + np.eye(num_cols)
    print(f'P :\n {P} \n L :\n {L} \n U :\n {U_matrix} \n')
    return (P,L,U_matrix)

Ya tenemos nuestro programa implementado, por lo cuál ahora haré algunos ejemplos para matríces de disintas dimensiones y capturando los posibles en donde no exista factorización posible en nuestra Matríz de entrada. Recordemos que la matríz resultante $LU$ corresponde a una permutación de la matríz original, y la ecuación que describe esto está dada por $$PA=LU$$ de este modo tenemos que $$A=P^TLU$$ que es lo que a continuación ilustraré con los ejemplos

In [4]:
P, L, U = factorizacion_PLU([[1,2],[3,4]])

La matriz 
 [[1. 2.]
 [3. 4.]] es cuadrada.
La matríz no es singular
P :
 [[0. 1.]
 [1. 0.]] 
 L :
 [[1.         0.        ]
 [0.33333333 1.        ]] 
 U :
 [[3.         4.        ]
 [0.         0.66666667]] 



In [5]:
P.T@L@U

matrix([[1., 2.],
        [3., 4.]])

In [6]:
P_2, L_2, U_2 = factorizacion_PLU([[1,2,0], [3,5,2], [0,2,1]])

La matriz 
 [[1. 2. 0.]
 [3. 5. 2.]
 [0. 2. 1.]] es cuadrada.
La matríz no es singular
P :
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 L :
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.16666667 1.        ]] 
 U :
 [[ 3.          5.          2.        ]
 [ 0.          2.          1.        ]
 [ 0.          0.         -0.83333333]] 



In [7]:
P_2.T@L_2@U_2

matrix([[1., 2., 0.],
        [3., 5., 2.],
        [0., 2., 1.]])

In [8]:
P_3, L_3, U_3 = factorizacion_PLU([[4,4,4,5], [2,3,1,4], [5,6,7,8], [5,4,3,2]])

La matriz 
 [[4. 4. 4. 5.]
 [2. 3. 1. 4.]
 [5. 6. 7. 8.]
 [5. 4. 3. 2.]] es cuadrada.
La matríz no es singular
P :
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 
 L :
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.00000000e-01 -3.00000000e-01  1.00000000e+00  0.00000000e+00]
 [ 8.00000000e-01  4.00000000e-01 -2.96059473e-16  1.00000000e+00]] 
 U :
 [[ 5.  6.  7.  8.]
 [ 0. -2. -4. -6.]
 [ 0.  0. -3. -1.]
 [ 0.  0.  0.  1.]] 



In [9]:
P_3.T@L_3@U_3

matrix([[4., 4., 4., 5.],
        [2., 3., 1., 4.],
        [5., 6., 7., 8.],
        [5., 4., 3., 2.]])

In [10]:
factorizacion_PLU([[1,2,3], [4,5,6]])

'La matriz no es cuadrada por lo tanto no es invertible.'

In [11]:
factorizacion_PLU([[0,1],[0,3]])

La matriz 
 [[0. 1.]
 [0. 3.]] es cuadrada.


'Tenemos que en la columna 1, es decir [[0. 0.]] \n                    el máximo es cero, entonces es singular y no se encuentra \n                    factorización'

In [12]:
P_fail, L_fail, U_fail = factorizacion_PLU([[1,0],[2,0]])

La matriz 
 [[1. 0.]
 [2. 0.]] es cuadrada.
La matríz no es singular
P :
 [[0. 1.]
 [1. 0.]] 
 L :
 [[1.  0. ]
 [0.5 1. ]] 
 U :
 [[2. 0.]
 [0. 0.]] 



In [13]:
P_fail.T@L_fail@U_fail

matrix([[1., 0.],
        [2., 0.]])

- ### Una función que dada una matriz A y un vector b, regrese la solución al sistema Ax=b.

Utilizando el hecho de que $PA=LU$, reescribimos el sistema de ecuaciones como $$PAx = Pb$$ $$\Rightarrow LUx = Pb$$
$$\Rightarrow Ux = L^{-1}Pb$$
$$\Rightarrow x = U^{-1}L^{-1}Pb$$

In [14]:
def solution_system(A,b): # El parámetro b es parte de la igualdad Ax = b
    try:
        P, L, U = factorizacion_PLU(A) 
        b = np.matrix(b)
        b = b.astype(float)
        return np.linalg.inv(U)@np.linalg.inv(L)@P@b #se espera que el parámetro b se ingrese como [[a,b,...],...]
    except: 
        return 'El sistema no tiene solución'

In [15]:
# Sea b = [1,2,3] vector columna de Ax = b
# nuestras b's se ejemplo:
b_1 = [[1],[2]]
b_2 = [[2],[16],[-2]]
b_3 = [[-23],[10],[2], [0]]

# nuestras A's de ejmplo:
A_1 = P.T@L@U 
A_2 = P_2.T@L_2@U_2
A_3 = P_3.T@L_3@U_3

# soluciones de nuestros sistemas propuestos
example_1 = solution_system(A_1, b_1)
print('------------------------------------------------------------------------')
example_2 = solution_system(A_2, b_2)
print('------------------------------------------------------------------------')
example_3 = solution_system(A_3, b_3)

La matriz 
 [[1. 2.]
 [3. 4.]] es cuadrada.
La matríz no es singular
P :
 [[0. 1.]
 [1. 0.]] 
 L :
 [[1.         0.        ]
 [0.33333333 1.        ]] 
 U :
 [[3.         4.        ]
 [0.         0.66666667]] 

------------------------------------------------------------------------
La matriz 
 [[1. 2. 0.]
 [3. 5. 2.]
 [0. 2. 1.]] es cuadrada.
La matríz no es singular
P :
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 L :
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.16666667 1.        ]] 
 U :
 [[ 3.          5.          2.        ]
 [ 0.          2.          1.        ]
 [ 0.          0.         -0.83333333]] 

------------------------------------------------------------------------
La matriz 
 [[4. 4. 4. 5.]
 [2. 3. 1. 4.]
 [5. 6. 7. 8.]
 [5. 4. 3. 2.]] es cuadrada.
La matríz no es singular
P :
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 
 L :
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1

Las soluciones que calcula el programa son las siguientes:

In [16]:
example_1

matrix([[0. ],
        [0.5]])

In [17]:
example_2

matrix([[ 7.6],
        [-2.8],
        [ 3.6]])

In [18]:
example_3

matrix([[-43.33333333],
        [ 62.26666667],
        [  5.06666667],
        [-23.8       ]])

Comprobemos si nuestra solución es correcta partiendo de que $Ax=b$

In [19]:
A_1@example_1 # Se espera que nos salga [[1],[2]]

matrix([[1.],
        [2.]])

In [20]:
A_2@example_2 # Se espera que nos salga [[2],[16],[-2]]

matrix([[ 2.],
        [16.],
        [-2.]])

In [21]:
A_3@example_3 # Se espera que nos salga [[-23],[10],[2], [0]]

matrix([[-2.30000000e+01],
        [ 1.00000000e+01],
        [ 2.00000000e+00],
        [ 5.68434189e-14]])

- ### Comprobaciones del funcionamiento del programa solucionador para entradas aleatorias de A y b. Una solución exitosa será cuando ||Ax-b||<E con E un número menor a 0.01 que ustedes establezcan.

In [22]:
def test_solution(A,b):
    matrix_norm = solution_system(A,b)
    Ax_b = A@matrix_norm - b
    return np.linalg.norm(Ax_b)

Ahora nos queda simular algunas matrices con sus respectivas soluciones

In [23]:
def random_matrix():
    A_matrix_random = []
    b_matrix_random = []
    lenght = random.randint(1,10)

    for i in range(lenght):
        rows_A = []
        for j in range(lenght):
            n = random.randint(-70,70)
            rows_A.append(n)
        A_matrix_random.append(rows_A)
        b_matrix_random.append([random.randint(-70,70)])
        
    return A_matrix_random, b_matrix_random

Ahora para finalizar hagamos la comprobación de la norma, para esto haré uso de un ciclo For y modificaré un poco el programa para la obtención de la factorización PLU sólo quitando las "impresiones" de si la matríz es o no cuadrada o singular.

In [24]:
def factorizacion_PLU_mod(A): 
    # El formato de A es [[a,b], [c,d], [],...]
    A_matrix = np.matrix(A)
    A_matrix = A_matrix.astype(float)
    # ¿La matríz es cuadrada e invertible?
    num_rows, num_cols = A_matrix.shape
    # Declaramos las matrices P, L y U
    P, L, U_matrix = np.identity(num_rows), np.zeros((num_rows,num_cols)), A_matrix.copy()
    
    # Paso 2, 3, 4 y 5 del algoritmo 
    count = 0
    while count < num_cols - 1: #tenemos que detenernos una columna antes 

        U_columna = U_matrix[count:,count]
        U_columna = np.reshape(U_columna, num_rows-count)
        max_value = np.amax(abs(U_columna)) 
        if max_value == 0: 
            return f'Tenemos que en la columna {count + 1}, es decir {U_columna} el máximo es cero, entonces es singular y no se encuentra factorización'        
        index_y, index_x = np.where(abs(U_matrix[count:,count]) == max_value)
        
        #cambio de renglones
        U_matrix[[index_x[0]+count, index_y[0]+count]] = U_matrix[[index_y[0]+count, index_x[0]+count]]
        P[[index_y[0]+count, index_x[0]+count]] = P[[index_x[0]+count, index_y[0]+count]]
        L[[index_y[0]+count, index_x[0]+count]] = L[[index_x[0]+count, index_y[0]+count]]

        for i in range(count+1, num_rows):
            L[i,count] = U_matrix[i,count] / U_matrix[count,count]
            U_matrix[i, :] = U_matrix[i, :] - L[i,count]*U_matrix[count,:]

        count += 1        
#    else:
        #print('La matríz no es singular')
    
    L = L + np.eye(num_cols)
#    print(f'P :\n {P} \n L :\n {L} \n U :\n {U_matrix} \n')
    return (P,L,U_matrix)


def solution_system_mod(A,b): # El parámetro b es parte de la igualdad Ax = b
    try:
        P, L, U = factorizacion_PLU_mod(A) 
        b = np.matrix(b)
        b = b.astype(float)
        return np.linalg.inv(U)@np.linalg.inv(L)@P@b #se espera que el parámetro b se ingrese como [[a,b,...],...]
    except: 
        return 'El sistema no tiene solución'
    
def test_solution_mod(A,b):
    matrix_norm = solution_system_mod(A,b)
    Ax_b = A@matrix_norm - b
    return np.linalg.norm(Ax_b)


In [25]:
def test_final(n):
    E = 0.009
    norma_test = 0

    for i in range(n):
        try: 
            A, b = random_matrix()
            norma_test = test_solution_mod(A, b)
            if norma_test < E:
                continue
            else: 
                return f'''Encontramos que
                        no se cumple la desigualdad 
                        en el sistema Ax = b = {A}x = {b}'''
        except: 
            '''Al parecer alguno de estos sistemas no se pudo solucionar, 
            ya sea por singularidad'''
    else:
        return f'Nuestro programa funciona bien con {n} iteraciones'

In [26]:
n = 10000
test_final(n)

'Nuestro programa funciona bien con 10000 iteraciones'

In [27]:
lesli = solution_system_mod([[1,4,1],[4,3,1],[2,1,4]], [[0],[6],[-9]])

In [28]:
lesli

matrix([[ 2.10638298],
        [ 0.31914894],
        [-3.38297872]])

In [29]:
np.matrix([[1,4,1],[4,3,1],[2,1,4]])@lesli

matrix([[ 0.],
        [ 6.],
        [-9.]])

In [30]:
solution_system_mod([[4,4,1,3,3], [4,1,1,3,2], [2,3,1,4,1], [5,2,4,5,5], [3,3,1,1,3]], [[-5],[7], [3], [4], [3]])

matrix([[ 36.        ],
        [ 17.33333333],
        [ 65.66666667],
        [-30.66666667],
        [-64.        ]])