# Factorización de Crout

In [1]:
# Librerías a utilizar
import numpy as np

- Una función que encuentre la factorización PLU de una matriz A. La función debe verificar que la matriz sea cuadrada e invertible. La prueba para saber si A es invertible debe hacerse con la condición del máximo distinto de cero.

Recordemos que la Factorización PLU, factoriza la matríz A como la multiplicación de tres matrices. Dicha factorización está dada por: $$A=PLU$$

In [2]:
# mis pruebas 
matrix_proof = np.matrix([[1,2,3],[4,5,6]])
2*matrix_proof[1,:]

matrix([[ 8, 10, 12]])

In [28]:
def factorizacion_PLU(A): 
    # El formato de A es [[a,b], [c,d], [],...]
    A_matrix = np.matrix(A)
    
    # ¿La matríz es cuadrada e invertible?
    num_rows, num_cols = A_matrix.shape
    # Declaramos las matrices P, L y U
    P, L, U_matrix = np.identity(num_rows), np.zeros((num_rows,num_cols)), A_matrix
    
    if num_rows == num_cols:
        print(f'La matriz \n {A_matrix} es cuadrada.')
    else:
        return 'La matriz no es cuadrada por lo tanto no es invertible.'
    
    # Paso 2 del algoritmo 
    count = 0
    while count < num_cols - 1: #tenemos que detenernos una columna antes 
        U_columna = U_matrix[:,count]
        U_columna = np.reshape(U_columna, num_rows)
        max_value = np.amax(U_columna)
        if max_value == 0: 
            return f'Tenemos que en la columna {count + 1}, es decir {U_columna} el máximo es cero, entonces es singular y no se encuentra factorización'        
        index_y,index_x = np.where(U_columna == max_value)
        
        #cambio de renglones
        U_matrix[[index_x[0], index_y[0]]] = U_matrix[[index_y[0], index_x[0]]]
        P[[index_y[0], index_x[0]]] = P[[index_x[0], index_y[0]]]
        L[[index_y[0], index_x[0]]] = L[[index_x[0], index_y[0]]]
        count += 1
    else:
        print('No es singular')
    print(f'Matrices cambiadas: \n U = {U_matrix} \n P ={P} \n L={L}')
    
    #Paso 3 del algoritmo
    '''
    for i in range(num_cols):
        for j in range(num_rows):
            if i < j:
                value_L = U_matrix[j,i] / U_matrix[i,i]
                print(f'{U_matrix[j,i]}, {U_matrix[i,i]}, entonces {value_L}')
                L[j,i] = value_L
            else:
                continue
    '''
    for i in range(num_rows):
        if 0 < i:
            value_L = U_matrix[i,0] / U_matrix[0,0] 
            print(f'{U_matrix[i,0]}, {U_matrix[0,0]}, entonces {value_L}')
            L[i,0] = value_L
            U_matrix[i, :] = U_matrix[i, :] - value_L*U_matrix[i,0]
#            U_matrix[i,1] = U_matrix[i,1] - value_L*U_matrix[1,1]
    print('Nuevo L: ', L)
    print('Nuevo U:' , U_matrix)

In [22]:
factorizacion_PLU([[5,6],[8,4]])
#factorizacion_PLU([[1,0],[3,4]])

La matriz 
 [[5 6]
 [8 4]] es cuadrada.
No es singular
Matrices cambiadas: 
 U = [[8 4]
 [5 6]] 
 P =[[0. 1.]
 [1. 0.]] 
 L=[[0. 0.]
 [0. 0.]]
5, 8, entonces 0.625
Nuevo L:  [[0.    0.   ]
 [0.625 0.   ]]
Nuevo U: [[8 4]
 [0 6]]


In [80]:
factorizacion_PLU([[1,2,3],[4,5,6]])

'La matriz no es cuadrada por lo tanto no es invertible.'

In [18]:
factorizacion_PLU([[0,0],[3,4]])

La matriz 
 [[0 0]
 [3 4]] es cuadrada.
No es singular
Matrices cambiadas: 
 A = [[3 4]
 [0 0]] 
 P =[[0. 1.]
 [1. 0.]] 
 L=[[0. 0.]
 [0. 0.]]
0, 3, entonces 0.0
Nuevo L:  [[0. 0.]
 [0. 0.]]


In [29]:
factorizacion_PLU([[1,2,0], [3,5,2], [0,2,1]])

La matriz 
 [[1 2 0]
 [3 5 2]
 [0 2 1]] es cuadrada.
No es singular
Matrices cambiadas: 
 U = [[3 5 2]
 [1 2 0]
 [0 2 1]] 
 P =[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] 
 L=[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1, 3, entonces 0.3333333333333333
0, 3, entonces 0.0
Nuevo L:  [[0.         0.         0.        ]
 [0.33333333 0.         0.        ]
 [0.         0.         0.        ]]
Nuevo U: [[3 5 2]
 [0 1 0]
 [0 2 1]]


In [19]:
factorizacion_PLU([[0,0],[0,4]])

La matriz 
 [[0 0]
 [0 4]] es cuadrada.


'Tenemos que en la columna 1, es decir [[0 0]] el máximo es cero, entonces es singular y no se encuentra factorización'